os: linux

dist: trusty

sudo: false

group: stable

language: c

compiler:
  - gcc
  # - clang

git:
  depth: false
  quiet: true

branches:
  only:
    - master
    # - development

addons:
  sonarcloud:
    organization: "elliottsobek-github"

before_install:
  - wget https://sonarqube.com/static/cpp/build-wrapper-linux-x86.zip

install:
  - unzip build-wrapper-linux-x86.zip
  - export PATH=$PWD/build-wrapper-linux-x86:$PATH

script:
  - build-wrapper-linux-x86-64 --out-dir . make all
  - make test
  # - cat $TRAVIS_BUILD_DIR/build/build-wrapper-dump.json
  - sonar-scanner

after_script:
  - rm -f build-wrapper-linux-x86.zip

before_deploy:
  script:
    - echo "BEFORE DEPLOY"

deploy:
  script:
    - echo "DEPLOY"

cache:
  - ccache
  directories:
    - $HOME/.sonar/cache
