# Travis CI Configuration.
# Copyright (C) 2018  Elliott Sobek
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

os: linux

dist: trusty

group: stable

sudo: false

git:
  depth: false
  quiet: true

branches:
  only:
    - master
    - development

language: c

compiler:
  - gcc
  - clang

cache:
  - ccache
  - $HOME/.sonar/cache

# addons:
#   sonarcloud:
#     organization: "elliottsobek-github"

stages:
  - Gather Packages
  - Install
  - Compile
  - Test
  - Tear Down
  - Deploy

jobs:
  include:
    - stage: Gather Packages
      script:
        - wget https://sonarqube.com/static/cpp/build-wrapper-linux-x86.zip
    - stage: Install
      script:
        - unzip build-wrapper-linux-x86.zip
        - export PATH=$PWD/build-wrapper-linux-x86:$PATH
    - stage: Compile
      addons:
        sonarcloud:
          organization: "elliottsobek-github"
      script:
        - build-wrapper-linux-x86-64 --out-dir . make
    - stage: Test
      script:
        - make test
        - sonar-scanner
    - stage: Tear Down
      script:
        - rm -f build-wrapper-linux-x86-64
    - stage: Deploy
      script:
        - echo "DEPLOY"

# before_install:
#   - wget https://sonarqube.com/static/cpp/build-wrapper-linux-x86.zip

# install:
  # - unzip build-wrapper-linux-x86.zip
  # - export PATH=$PWD/build-wrapper-linux-x86:$PATH

# script:
#   - build-wrapper-linux-x86-64 --out-dir . make
#   - make test
#   # - cat $TRAVIS_BUILD_DIR/build/build-wrapper-dump.json
#   - sonar-scanner

# after_script:
#   - rm -f build-wrapper-linux-x86.zip

# before_deploy:
#   script:
#     - echo "BEFORE DEPLOY"

# deploy:
#   script:
#     - echo "BEFORE DEPLOY"

# cache:
#   - ccache
#   - $HOME/.sonar/cache
