os: linux

dist: trusty

sudo: false

group: stable

language: C

compiler: gcc

branches:
  only: master

addons:
  sonarcloud:
    organization: "elliottsobek-github"

script:
  - ./test.bash
  - sonar-scanner
