os: linux

dist: trusty

sudo: false

group: stable

language: c

compiler:
  - gcc
  - clang

git:
  depth: false
  quiet: true

branches:
  only:
    - master
    - development

addons:
  sonarcloud:
    organization: "elliottsobek-github"

before_install:
  - wget https://sonarqube.com/static/cpp/build-wrapper-linux-x86.zip
  - unzip build-wrapper-linux-x86.zip
  - export PATH=$PWD/build-wrapper-linux-x86:$PATH

script:
  - make
  - build-wrapper-linux-x86-64 --out-dir $TRAVIS_BUILD_DIR/build make test
  - sonar-scanner

cache:
  - ccache
  - $HOME/.sonar/cache
